// <auto-generated />
using System;
using AppleShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppleShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250617062444_InitMig")]
    partial class InitMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppleShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("AppleShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Latest iPhones",
                            Name = "iPhones"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple Laptops",
                            Name = "MacBooks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apple Accessories",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apple Wearables",
                            Name = "Wearables"
                        });
                });

            modelBuilder.Entity("AppleShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AppleShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AppleShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest iPhone with advanced features",
                            ImageUrl = "/images/iphone15.jpg",
                            Name = "iPhone 15",
                            Price = 999.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Powerful laptop with M1 Pro chip",
                            ImageUrl = "/images/macbookpro.jpg",
                            Name = "MacBook Pro 14-inch",
                            Price = 1999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Noise-cancelling earphones",
                            ImageUrl = "/images/airpodspro.jpg",
                            Name = "AirPods Pro",
                            Price = 249.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Advanced smartwatch with health features",
                            ImageUrl = "/images/applewatch.jpg",
                            Name = "Apple Watch Series 8",
                            Price = 399.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Tablet with M1 chip for professional use",
                            ImageUrl = "/images/ipadpro.jpg",
                            Name = "iPad Pro",
                            Price = 1099.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lightweight laptop with M1 chip",
                            ImageUrl = "/images/macbookair.jpg",
                            Name = "MacBook Air",
                            Price = 999.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Smart speaker with great sound quality",
                            ImageUrl = "/images/homepodmini.jpg",
                            Name = "HomePod Mini",
                            Price = 99.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Keyboard designed for iPad Pro",
                            ImageUrl = "/images/magickeyboard.jpg",
                            Name = "Magic Keyboard",
                            Price = 299.99m,
                            Stock = 70
                        });
                });

            modelBuilder.Entity("AppleShop.Models.CartItem", b =>
                {
                    b.HasOne("AppleShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AppleShop.Models.OrderItem", b =>
                {
                    b.HasOne("AppleShop.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppleShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AppleShop.Models.Product", b =>
                {
                    b.HasOne("AppleShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AppleShop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AppleShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
