// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zawod.Data;

#nullable disable

namespace Zawod.Migrations
{
    [DbContext(typeof(ZawodDbContext))]
    [Migration("20250423063028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Zawod.Data.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("Zawod.Data.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProcessingTime")
                        .HasColumnType("REAL");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Zawod.Data.MachineDetail", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MachineId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("MachineDetails");
                });

            modelBuilder.Entity("Zawod.Data.Modification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetailId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LaborIntensity")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetailId");

                    b.ToTable("Modifications");
                });

            modelBuilder.Entity("Zawod.Data.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Zawod.Data.Machine", b =>
                {
                    b.HasOne("Zawod.Data.Shop", "Shop")
                        .WithMany("Machines")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Zawod.Data.MachineDetail", b =>
                {
                    b.HasOne("Zawod.Data.Detail", "Detail")
                        .WithMany("MachineDetails")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zawod.Data.Machine", "Machine")
                        .WithMany("MachineDetails")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Zawod.Data.Modification", b =>
                {
                    b.HasOne("Zawod.Data.Detail", "Detail")
                        .WithMany("Modifications")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("Zawod.Data.Detail", b =>
                {
                    b.Navigation("MachineDetails");

                    b.Navigation("Modifications");
                });

            modelBuilder.Entity("Zawod.Data.Machine", b =>
                {
                    b.Navigation("MachineDetails");
                });

            modelBuilder.Entity("Zawod.Data.Shop", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
