namespace WindowsForms5
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.ListBox listBoxOriginal;
        private System.Windows.Forms.ListBox listBoxResult;
        private System.Windows.Forms.Button fillButton;
        private System.Windows.Forms.Button calculateButton;
        private System.Windows.Forms.Label labelOriginal;
        private System.Windows.Forms.Label labelResult;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the designer

        private void InitializeComponent()
        {
            this.listBoxOriginal = new System.Windows.Forms.ListBox();
            this.listBoxResult = new System.Windows.Forms.ListBox();
            this.fillButton = new System.Windows.Forms.Button();
            this.calculateButton = new System.Windows.Forms.Button();
            this.labelOriginal = new System.Windows.Forms.Label();
            this.labelResult = new System.Windows.Forms.Label();

            this.SuspendLayout();

            // ListBox for original array
            this.listBoxOriginal.FormattingEnabled = true;
            this.listBoxOriginal.Location = new System.Drawing.Point(12, 30);
            this.listBoxOriginal.Size = new System.Drawing.Size(200, 160);

            // ListBox for result array
            this.listBoxResult.FormattingEnabled = true;
            this.listBoxResult.Location = new System.Drawing.Point(220, 30);
            this.listBoxResult.Size = new System.Drawing.Size(200, 160);

            // Button to fill the array
            this.fillButton.Location = new System.Drawing.Point(12, 200);
            this.fillButton.Size = new System.Drawing.Size(100, 30);
            this.fillButton.Text = "Заполнить";
            this.fillButton.Click += new System.EventHandler(this.FillButton_Click);

            // Button to calculate the result
            this.calculateButton.Location = new System.Drawing.Point(220, 200);
            this.calculateButton.Size = new System.Drawing.Size(100, 30);
            this.calculateButton.Text = "ПУСК";
            this.calculateButton.Click += new System.EventHandler(this.CalculateButton_Click);

            // Label for original array
            this.labelOriginal.AutoSize = true;
            this.labelOriginal.Location = new System.Drawing.Point(12, 10);
            this.labelOriginal.Text = "Исходный массив";

            // Label for result array
            this.labelResult.AutoSize = true;
            this.labelResult.Location = new System.Drawing.Point(220, 10);
            this.labelResult.Text = "Полученный массив";

            // Form settings
            this.ClientSize = new System.Drawing.Size(450, 250);
            this.Controls.Add(this.listBoxOriginal);
            this.Controls.Add(this.listBoxResult);
            this.Controls.Add(this.fillButton);
            this.Controls.Add(this.calculateButton);
            this.Controls.Add(this.labelOriginal);
            this.Controls.Add(this.labelResult);
            this.Name = "Form1";
            this.Text = "Одномерные массивы";

            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion
    }
}
